name: Deploy to Production using RSYNC
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Project
        run: |
          npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: RSYNC new version to production
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./dist/ ${{ secrets.DEPLOY_SERVER }}
